(() => {
 const $=s=>document.querySelector(s),api=window.adminAPI;
 let content,revision,dirty=false,tab='profile',busy=false,undo=null,saveAttempt=null,publicationRun=0,editVersion=0;
 if(api.online){$('#setup-note').textContent='使用管理员密码登录，仅本人可编辑。';$('#save-content').textContent='保存并发布';$('#save-note').textContent='保存后自动更新仓库并发布。页面会显示发布进度，无需启动本机服务。PPT 请先导出图片或 PDF。';}
 async function watchPublication(rev){const run=++publicationRun;for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,5000));if(run!==publicationRun)return;try{const result=await api.call('/publication?revision='+rev);if(run!==publicationRun)return;if(result.status==='published'){$('#save-status').textContent='已发布，刷新网站即可看到更新。';return;}if(result.status==='failed'){$('#save-status').textContent='资料已保存，但网站发布失败，请检查仓库的发布记录。';return;}$('#save-status').textContent='资料已保存，网站正在发布…';}catch{$('#save-status').textContent='资料已保存，暂未获取到发布状态，可稍后刷新网站查看。';return;}}$('#save-status').textContent='资料已保存，发布仍在处理中，可稍后刷新网站查看。';}
 const clone=v=>structuredClone(v);
 function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
 function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
 function mark(){dirty=true;++editVersion;++publicationRun;$('#save-status').textContent='有未保存的修改';}
 function report(e){$('#save-status').textContent=e.message;if(e.status===401){api.setToken('');$('#workspace').hidden=true;$('#login-panel').hidden=false;$('#login-status').textContent=e.message;}}
 function field(container,obj,key,label,{area=false,type='text',wide=false}={}){const l=el('label',label,wide?'wide':'');const input=el(area?'textarea':'input');input.value=obj[key]||'';input.dataset.field=key;if(!area)input.type=type;input.maxLength=area?8000:500;input.oninput=()=>{obj[key]=input.value;if(obj.id)obj.managed=true;if(obj===content.profile||content.profile.education.includes(obj))content.profile.managed=true;mark();};l.append(input);container.append(l);return input;}
 function reorder(list,index,to){if(list===content.profile.education)content.profile.managed=true;if(to<0||to>=list.length)return;const item=list.splice(index,1)[0];list.splice(to,0,item);mark();render();}
 function remove(list,index){if(list===content.profile.education)content.profile.managed=true;undo={list,item:list[index],index};list.splice(index,1);mark();render();}
 function recordActions(container,list,index){const row=el('div',undefined,'record-actions');const up=button('上移',()=>reorder(list,index,index-1)),down=button('下移',()=>reorder(list,index,index+1));up.disabled=index===0;down.disabled=index===list.length-1;row.append(up,down,button('移除',()=>remove(list,index)));container.append(row);}
 async function filePick(accept,multiple,onFiles){const input=el('input');input.type='file';input.accept=accept;input.multiple=multiple;input.onchange=async()=>{if(!input.files.length||busy)return;busy=true;$('#save-content').disabled=true;$('#save-status').textContent='正在上传附件…';try{const paths=[];for(const file of input.files)paths.push(await api.upload(file));await onFiles(paths);mark();render();}catch(e){report(e);}finally{busy=false;$('#save-content').disabled=false;}};input.click();}
 function uploadField(container,obj,key,label,accept){const box=el('div',undefined,'wide'),heading=el('p',label);box.append(heading);const row=el('div',undefined,'media-row');if(obj[key]){if(key==='cover'){const img=el('img');img.src=api.asset(obj[key]);img.alt='项目封面预览';row.append(img);}else{const a=el('a','查看附件 ↗');a.href=api.asset(obj[key]);a.target='_blank';a.rel='noopener';row.append(a);}row.append(button('移除附件',()=>{obj[key]='';obj.managed=true;mark();render();}));}row.append(button(obj[key]?'更换文件':'上传文件',()=>filePick(accept,false,paths=>{obj[key]=paths[0];obj.managed=true;})));box.append(row);container.append(box);}
 function renderProfile(editor){const box=el('section',undefined,'editor-card'),grid=el('div',undefined,'form-grid');field(grid,content.profile,'welcome','欢迎页介绍',{area:true,wide:true});field(grid,content.profile,'intro','个人简介',{area:true,wide:true});field(grid,content.profile,'email','联系邮箱',{type:'email',wide:true});box.append(grid);editor.append(box,el('h2','教育背景'));content.profile.education.forEach((record,i)=>{const card=el('section',undefined,'editor-card'),g=el('div',undefined,'form-grid');field(g,record,'label','阶段');field(g,record,'title','学校 / 课程');field(g,record,'detail','专业 / 补充说明',{wide:true});card.append(g);recordActions(card,content.profile.education,i);editor.append(card);});editor.append(button('＋ 添加教育经历',()=>{content.profile.education.push({label:'',title:'',detail:''});content.profile.managed=true;mark();render();}));}
 function renderRecords(editor,key){const list=content[key],project=key==='projects';list.forEach((record,index)=>{const card=el('details',undefined,'editor-card');card.open=!record.title;const summary=el('summary',record.title||'新'+(project?'项目':'经历'));summary.append(el('small',project?record.type:record.company));card.append(summary);const grid=el('div',undefined,'form-grid');field(grid,record,'title',project?'项目名称':'经历标题',{wide:true});if(project){field(grid,record,'type','项目类型');field(grid,record,'year','年份 / 状态');field(grid,record,'headline','封面短句',{area:true,wide:true});field(grid,record,'description','项目简介',{area:true,wide:true});for(const [k,label] of [['problem','解决什么问题'],['process','我做了什么'],['result','结果与进展']])field(grid,record,k,label,{area:true,wide:true});field(grid,record,'link','项目链接（GitHub 或演示地址）',{type:'url',wide:true});uploadField(grid,record,'cover','封面图片','image/jpeg,image/png,image/webp');uploadField(grid,record,'pdf','项目展示 PDF','application/pdf');const slides=el('div',undefined,'wide');slides.append(el('p','展示页 · 按浏览顺序排列'),button('＋ 上传展示图片',()=>filePick('image/jpeg,image/png,image/webp',true,paths=>{record.slides.push(...paths);record.managed=true;})));const strip=el('div',undefined,'slide-list');record.slides.forEach((src,i)=>{const item=el('div'),img=el('img');img.src=api.asset(src);img.alt='第 '+(i+1)+' 页';item.append(img,button('←',()=>reorder(record.slides,i,i-1)),button('→',()=>reorder(record.slides,i,i+1)),button('删除',()=>{record.slides.splice(i,1);mark();render();}));strip.append(item);});slides.append(strip);grid.append(slides);}else{field(grid,record,'company','公司 / 组织');field(grid,record,'date','起止时间');field(grid,record,'description','工作内容',{area:true,wide:true});field(grid,record,'highlight','成果 / 收获',{area:true,wide:true});const proxy={tags:record.tags.join('、')};const input=field(grid,proxy,'tags','标签（用顿号分隔）',{wide:true});input.oninput=()=>{record.tags=input.value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean);record.managed=true;mark();};}
 field(grid,record,'narration','人物简短讲解文稿',{area:true,wide:true});grid.append(el('small','新文稿先用于文字讲解，不会套用旧录音。后续可再生成匹配的声音。','wide'));card.append(grid);recordActions(card,list,index);editor.append(card);});if(!list.length)editor.append(el('p','还没有内容，点击右上角添加。','empty-editor'));}
 function renderPhotos(editor){const list=content.photos,grid=el('div',undefined,'admin-photos');list.forEach((photo,index)=>{const card=el('article',undefined,'admin-photo');card.dataset.index=index;const clip=button('',()=>{});clip.className='clip';clip.setAttribute('aria-label','拖动夹子排序：'+photo.caption);clip.title='拖动排序，或用左右方向键';clip.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();reorder(list,index,index+(e.key==='ArrowLeft'?-1:1));}};let active=false,target=null;clip.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();clip.setPointerCapture(e.pointerId);active=true;};clip.onpointermove=e=>{if(!active)return;grid.querySelectorAll('[data-drop]').forEach(x=>delete x.dataset.drop);const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('.admin-photo');target=hit?Number(hit.dataset.index):null;if(hit)hit.dataset.drop=true;};clip.onpointerup=()=>{if(active&&target!==null)reorder(list,index,target);active=false;};clip.onpointercancel=()=>{active=false;grid.querySelectorAll('[data-drop]').forEach(x=>delete x.dataset.drop);};const img=el('img');img.src=api.asset(photo.thumbnail||photo.src);img.alt=photo.alt||photo.caption;card.append(clip,img);const text=el('textarea');text.value=photo.caption;text.maxLength=100;text.setAttribute('aria-label','照片说明');text.oninput=()=>{photo.caption=text.value;mark();};card.append(text);const row=el('div',undefined,'record-actions');row.append(button('删除',()=>remove(list,index)));card.append(row);grid.append(card);});editor.append(grid);if(!list.length)editor.append(el('p','还没有照片，上传后会挂到网站相册。','empty-editor'));}
 function render(){const editor=$('#editor');editor.replaceChildren();document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.tab===tab)));const title=el('div',undefined,'editor-title');title.append(el('h2',{profile:'简介与联系',projects:'项目作品',experiences:'个人经历',photos:'生活相册'}[tab]));if(tab==='projects'||tab==='experiences')title.append(button('＋ 添加'+(tab==='projects'?'项目':'经历'),()=>{const record=tab==='projects'?{title:'',type:'',year:'',headline:'',description:'',problem:'',process:'',result:'',link:'',cover:'',pdf:'',slides:[],narration:''}:{title:'',date:'',company:'',description:'',highlight:'',tags:[],narration:''};content[tab].unshift({id:crypto.randomUUID(),managed:true,...record});mark();render();editor.querySelector('input')?.focus();}));if(tab==='photos')title.append(button('＋ 上传照片',()=>filePick('image/jpeg,image/png,image/webp',true,paths=>{content.photos.push(...paths.map(src=>({id:crypto.randomUUID(),src,caption:'记住这一刻。',alt:'生活照片'})));})));if(undo)title.append(button('撤销上次删除',()=>{undo.list.splice(undo.index,0,undo.item);undo=null;mark();render();}));editor.append(title);if(tab==='profile')renderProfile(editor);else if(tab==='photos')renderPhotos(editor);else renderRecords(editor,tab);}
 async function oldPhotos(){const defaults=clone(window.portfolioPhotos);try{return await new Promise(resolve=>{const req=indexedDB.open('ruan-life-album',1);req.onupgradeneeded=()=>req.result.createObjectStore('album');req.onerror=()=>resolve(defaults);req.onsuccess=()=>{const db=req.result,r=db.transaction('album').objectStore('album').get('state');r.onerror=()=>{db.close();resolve(defaults);};r.onsuccess=()=>{const s=r.result;db.close();if(!s){resolve(defaults);return;}const rows=defaults.filter(p=>!(s.removed||[]).includes(p.id)).map(p=>({...p,caption:s.captions?.[p.id]||p.caption})).concat(s.custom||[]),map=new Map(rows.map(p=>[p.id,p]));resolve([...(s.order||[]).flatMap(id=>{const p=map.get(id);map.delete(id);return p?[p]:[];}),...map.values()]);};};});}catch{return defaults;}}
 async function load(){const data=await api.call('/session');if(!dirty){revision=data.revision;content=clone(data.content);}else if(revision!==data.revision){$('#save-status').textContent='网站已有更新，当前草稿已保留，请先导出备份再重新加载。';}if(!content.photos)content.photos=await oldPhotos();$('#login-panel').hidden=true;$('#workspace').hidden=false;$('#password').value='';tab=['profile','projects','experiences','photos'].includes(location.hash.slice(1))?location.hash.slice(1):'profile';render();}
 $('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('#login-status').textContent='正在验证…';try{const result=await api.call('/login',{password:$('#password').value});api.setToken(result.token);await load();}catch(error){$('#login-status').textContent=error.message;}finally{b.disabled=false;}};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;history.replaceState(null,'','#'+tab);render();});
 $('#save-content').onclick=async()=>{if(busy)return;busy=true;$('#save-content').disabled=true;$('#save-status').textContent='正在保存…';try{for(const group of ['projects','experiences'])if(content[group].some(r=>!r.title.trim()))throw Error('请补全项目或经历标题后保存');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(content.profile.email))throw Error('请输入正确的邮箱地址');for(const photo of content.photos){if(photo.src.startsWith('data:')){const blob=await(await fetch(photo.src)).blob();photo.src=await api.upload(new File([blob],'photo',{type:blob.type}));delete photo.thumbnail;}}
 const payload=JSON.stringify({content,revision});if(!saveAttempt||saveAttempt.payload!==payload)saveAttempt={payload,id:crypto.randomUUID()};const savedVersion=editVersion;const result=await api.call('/save',{content,revision,operationId:saveAttempt.id});revision=result.revision;dirty=editVersion!==savedVersion;undo=null;saveAttempt=null;if(dirty){$('#save-status').textContent='上一版已保存；你刚才的新修改尚未保存。';}else if(api.online){$('#save-status').textContent='资料已保存，正在发布到网站…';watchPublication(result.revision);}else $('#save-status').textContent='已保存到本地网站，刷新预览即可查看。尚未部署上线。';}catch(e){report(e);}finally{busy=false;$('#save-content').disabled=false;}};
 $('#export-content').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='ruan-content-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('#logout').onclick=async()=>{if(dirty&&!confirm('有未保存的修改，确定退出并放弃吗？'))return;try{await api.call('/logout',{});api.setToken('');location.reload();}catch(e){report(e);}};
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 (async()=>{try{const state=await api.call('/status');$('#login-status').textContent=state.configured?'输入你设置的管理员密码。':api.online?'在线后台尚未完成配置，暂时不能登录。':'尚未设置密码。请先运行项目文件夹里的「设置管理密码.cmd」，再回来登录。';try{await load();}catch(e){if(e.status!==401)throw e;}}catch(e){$('#login-status').textContent=e.message;}})();
})();
