(() => {
 const gallery=document.querySelector('.life-gallery'),photos=window.portfolioPhotos;
 const isOwner=false; // Editing now lives behind the authenticated management page.
 if(new URLSearchParams(location.search).get('album')==='edit'){location.replace('admin.html#photos');return;}
 const published=window.PORTFOLIO_CONTENT?.photos;
 if(published)photos.splice(0,photos.length,...published);
 gallery.dataset.editing=String(isOwner);
 const baseIds=new Set(photos.map(p=>p.id)),removed=new Set();let db;
 const storage=new Promise((resolve,reject)=>{const request=indexedDB.open('ruan-life-album',1);request.onupgradeneeded=()=>request.result.createObjectStore('album');request.onsuccess=()=>{db=request.result;resolve(db);};request.onerror=()=>reject(request.error);});
 async function save(next){if(!isOwner)throw new Error('Read-only album');await storage;return new Promise((resolve,reject)=>{const tx=db.transaction('album','readwrite');tx.objectStore('album').put({order:next.map(p=>p.id),custom:next.filter(p=>!baseIds.has(p.id)),captions:Object.fromEntries(next.filter(p=>baseIds.has(p.id)).map(p=>[p.id,p.caption])),removed:[...removed]},'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 const actions=document.createElement('div');actions.className='album-actions';actions.innerHTML='<span role="status"></span><button type="button" data-album-undo hidden>撤销删除</button><button type="button" data-album-export>导出相册备份</button>';gallery.after(actions);actions.hidden=!isOwner;
 const status=actions.querySelector('[role=status]');let undo;
 let draggedId=null,orderBusy=false;
 function addOrderControls(figure,photo,index){
  const clip=document.createElement(isOwner?'button':'span');clip.className='album-clip';
  if(!isOwner){clip.setAttribute('aria-hidden','true');figure.append(clip);return;}
  clip.type='button';clip.title='拖动夹子调整顺序；也可用左右方向键';clip.setAttribute('aria-label',`拖动夹子排序：${photo.caption}`);
  clip.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();movePhoto(photo.id,index+(e.key==='ArrowLeft'?-1:1));}});
  let startPoint,targetIndex=null,active=false;
  clip.addEventListener('pointerdown',e=>{if(e.button!==0||orderBusy||gallery.querySelector('.photo-caption-form'))return;e.preventDefault();clip.focus({preventScroll:true});clip.setPointerCapture(e.pointerId);startPoint={x:e.clientX,y:e.clientY};active=false;targetIndex=null;});
  clip.addEventListener('pointermove',e=>{if(!startPoint)return;if(!active&&Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)<6)return;if(!active){active=true;draggedId=photo.id;figure.dataset.dragging='true';window.ruanAutoGuide?.pause();window.ruanPresenter?.finish();}const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.album-print');gallery.querySelectorAll('[data-drop-target]').forEach(el=>delete el.dataset.dropTarget);targetIndex=null;if(target&&gallery.contains(target)){targetIndex=target.classList.contains('album-empty')?photos.length-1:photos.findIndex(p=>p.id===target.dataset.photoId);target.dataset.dropTarget='true';}});
  const end=e=>{const to=targetIndex,drop=active&&e.type==='pointerup';startPoint=null;active=false;targetIndex=null;clearDrag();if(clip.hasPointerCapture(e.pointerId))clip.releasePointerCapture(e.pointerId);if(drop&&to!==null)movePhoto(photo.id,to);};
  clip.addEventListener('pointerup',end);clip.addEventListener('pointercancel',end);clip.addEventListener('lostpointercapture',()=>{startPoint=null;active=false;clearDrag();});figure.append(clip);
 }
 function clearDrag(){draggedId=null;gallery.querySelectorAll('[data-dragging],[data-drop-target]').forEach(el=>{delete el.dataset.dragging;delete el.dataset.dropTarget;});}
 async function movePhoto(id,to){
  const from=photos.findIndex(p=>p.id===id);if(!isOwner||orderBusy||from<0||to<0||to>=photos.length||from===to)return;
  if(gallery.querySelector('.photo-caption-form')){status.textContent='先保存或取消正在编辑的文字，再调整顺序。';return;}
  window.ruanAutoGuide?.pause();window.ruanPresenter?.finish();orderBusy=true;const next=[...photos],photo=next.splice(from,1)[0];next.splice(to,0,photo);
  try{await save(next);photos.splice(0,photos.length,...next);render();status.textContent=`已移到第 ${to+1} 张，顺序保存在此浏览器。`;gallery.querySelector(`[data-photo-id="${id}"] .album-clip`)?.focus({preventScroll:true});}catch{status.textContent='顺序保存失败，请重试。';}finally{orderBusy=false;}
 }
 const viewer=document.createElement('dialog');viewer.className='photo-viewer';viewer.setAttribute('aria-label','生活相册大图');
 viewer.innerHTML='<button type="button" class="photo-close" aria-label="关闭大图">×</button><figure><img alt=""/><figcaption></figcaption></figure><div class="photo-viewer-controls"><button type="button" data-photo-prev aria-label="上一张照片">← 上一张</button><span aria-live="polite"></span><button type="button" data-photo-next aria-label="下一张照片">下一张 →</button></div>';
 document.body.append(viewer);let selected=0,opener;
 function show(index){selected=(index+photos.length)%photos.length;const photo=photos[selected],img=viewer.querySelector('img');img.src=photo.src;img.alt=photo.alt;viewer.querySelector('figcaption').textContent=photo.caption;viewer.querySelector('[aria-live]').textContent=`${selected+1} / ${photos.length}`;}
 function open(index,button){opener=button;window.ruanAutoGuide?.pause();window.ruanPresenter?.finish();window.ruanPresenter?.walker.stop();show(index);viewer.showModal();viewer.querySelector('.photo-close').focus();}
 function render(){gallery.replaceChildren();photos.forEach((photo,index)=>{const figure=document.createElement('figure');figure.className='album-print';figure.dataset.photoId=photo.id;const button=document.createElement('button');button.type='button';button.className='photo-thumbnail';button.setAttribute('aria-label',`放大照片：${photo.alt}`);button.setAttribute('aria-haspopup','dialog');const img=document.createElement('img');const size=()=>{const width=photo.width||img.naturalWidth,height=photo.height||img.naturalHeight;if(!width||!height)return;figure.classList.toggle('is-landscape',width/height>1.2);drawWires();};img.addEventListener('load',size);if(photo.width&&photo.height)size();img.src=photo.thumbnail||photo.src;img.alt=photo.alt;img.loading='lazy';img.decoding='async';button.append(img);const caption=document.createElement('figcaption');const edit=document.createElement(isOwner?'button':'span');edit.className='photo-caption-edit';edit.type='button';edit.textContent=photo.caption;if(isOwner){edit.setAttribute('aria-label',`编辑照片文字：${photo.caption}`);edit.title='点击编辑文字';edit.addEventListener('click',()=>editCaption(photo,caption));}caption.append(edit);const del=document.createElement('button');del.className='photo-delete';del.type='button';del.textContent='×';del.setAttribute('aria-label',`删除照片：${photo.alt}`);del.addEventListener('click',()=>remove(photo));figure.append(button,caption);if(isOwner)figure.append(del);addOrderControls(figure,photo,index);gallery.append(figure);button.addEventListener('click',()=>open(index,button));});
 const empty=document.createElement('figure');empty.className='album-print album-empty';
 if(isOwner){empty.innerHTML='<button class="photo-add" type="button" aria-haspopup="dialog"><b aria-hidden="true">＋</b><span>挂一张新照片</span></button><figcaption>下一段日常，留在这里。</figcaption>';empty.querySelector('button').addEventListener('click',()=>{opener=empty.querySelector('button');window.ruanAutoGuide?.pause();window.ruanPresenter?.finish();upload.showModal();});}
 else{empty.innerHTML='<div class="photo-coming-soon">尽情期待</div><figcaption>下一段日常，慢慢更新。</figcaption>';}
 const clip=document.createElement('span');clip.className='album-clip';clip.setAttribute('aria-hidden','true');empty.append(clip);gallery.append(empty);drawWires();}
 let wireFrame;
 function drawWires(){cancelAnimationFrame(wireFrame);wireFrame=requestAnimationFrame(()=>{gallery.querySelector('.album-wires')?.remove();const wires=document.createElement('div');wires.className='album-wires';wires.setAttribute('aria-hidden','true');const rows=new Set([...gallery.querySelectorAll('.album-print')].map(el=>el.offsetTop));for(const top of rows){const line=document.createElement('span');line.style.top=top-20+'px';wires.append(line);}gallery.prepend(wires);});}
 new ResizeObserver(drawWires).observe(gallery);
 function editCaption(photo,caption){if(!isOwner)return;window.ruanAutoGuide?.pause();window.ruanPresenter?.finish();const form=document.createElement('form');form.className='photo-caption-form';form.innerHTML='<textarea rows="3" maxlength="100" aria-label="照片文字" required></textarea><div><button type="submit">保存</button><button type="button" data-cancel>取消</button></div><span role="status"></span>';const input=form.querySelector('textarea');input.value=photo.caption;caption.replaceChildren(form);input.focus({preventScroll:true});input.select();drawWires();const restore=()=>{render();gallery.querySelector(`[data-photo-id="${photo.id}"] .photo-caption-edit`)?.focus({preventScroll:true});};form.querySelector('[data-cancel]').addEventListener('click',restore);form.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();restore();}else if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();form.requestSubmit();}});form.addEventListener('submit',async e=>{e.preventDefault();const value=input.value.trim();if(!value){form.querySelector('[role=status]').textContent='写一句话再保存吧。';return;}const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const next=photos.map(p=>p===photo?{...p,caption:value}:p);await save(next);photo.caption=value;status.textContent='照片文字已保存在此浏览器。';restore();}catch{form.querySelector('[role=status]').textContent='保存失败，请重试。';submit.disabled=false;}});}
 async function remove(photo){if(!isOwner)return;const index=photos.indexOf(photo),next=photos.filter(p=>p!==photo);if(baseIds.has(photo.id))removed.add(photo.id);try{await save(next);photos.splice(index,1);undo={photo,index};render();actions.querySelector('[data-album-undo]').hidden=false;status.textContent='已从本机相册移除，可撤销。';actions.querySelector('[data-album-undo]').focus({preventScroll:true});}catch{removed.delete(photo.id);status.textContent='保存失败，照片没有删除。';}}
 actions.querySelector('[data-album-undo]').addEventListener('click',async()=>{if(!undo)return;const {photo,index}=undo,next=[...photos];next.splice(index,0,photo);removed.delete(photo.id);try{await save(next);photos.splice(index,0,photo);undo=null;render();actions.querySelector('[data-album-undo]').hidden=true;status.textContent='照片已恢复。';gallery.querySelectorAll('.photo-thumbnail')[index].focus({preventScroll:true});}catch{if(baseIds.has(photo.id))removed.add(photo.id);status.textContent='恢复失败，请重试。';}});
 actions.querySelector('[data-album-export]').addEventListener('click',()=>{const data=JSON.stringify({version:1,photos},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ruan-life-album.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='备份包含新增照片；可交给网站维护者发布。';});
 const upload=document.createElement('dialog');upload.className='photo-viewer photo-upload-dialog';upload.setAttribute('aria-label','添加生活照片');upload.innerHTML='<button type="button" class="photo-close" aria-label="取消添加">×</button><form class="photo-upload-form"><h3>挂一张新照片</h3><label>选择照片<input type="file" accept="image/jpeg,image/png,image/webp" required/></label><img hidden alt="待添加照片预览"/><label>写一句日常<input name="caption" maxlength="100" placeholder="记住这一刻。"/></label><p>照片保存在此浏览器，刷新后仍在。暂未同步到公开网站，可导出备份后发布。</p><p role="status"></p><button type="submit">挂上照片</button></form>';document.body.append(upload);
 let pending,previewURL;const form=upload.querySelector('form'),fileInput=form.querySelector('[type=file]'),uploadStatus=form.querySelector('[role=status]'),preview=form.querySelector('img');
 fileInput.addEventListener('change',()=>{pending=null;if(previewURL)URL.revokeObjectURL(previewURL);preview.hidden=true;const file=fileInput.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024){uploadStatus.textContent='请选择 15 MB 以内的 JPG、PNG 或 WebP 照片。';fileInput.value='';return;}pending=file;previewURL=URL.createObjectURL(file);preview.src=previewURL;preview.hidden=false;uploadStatus.textContent='';});
 form.addEventListener('submit',async e=>{e.preventDefault();if(!pending)return;const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const file=pending,src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const image=new Image();image.src=src;await image.decode();const canvas=document.createElement('canvas'),scale=Math.min(1,480/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const caption=form.elements.caption.value.trim()||'记住这一刻。',photo={id:crypto.randomUUID(),src,width:image.naturalWidth,height:image.naturalHeight,thumbnail:canvas.toDataURL('image/webp',.85),caption,alt:caption};await save([...photos,photo]);photos.push(photo);render();status.textContent='照片已挂上，并保存在此浏览器。';upload.close();gallery.querySelectorAll('.photo-thumbnail')[photos.length-1].focus({preventScroll:true});}catch{uploadStatus.textContent='未能保存照片，请检查图片或浏览器存储空间后重试。';}finally{submit.disabled=false;}});
 upload.querySelector('.photo-close').addEventListener('click',()=>upload.close());upload.addEventListener('close',()=>{form.reset();pending=null;preview.hidden=true;if(previewURL)URL.revokeObjectURL(previewURL);uploadStatus.textContent='';if(opener?.isConnected)opener.focus({preventScroll:true});});
 viewer.querySelector('.photo-close').addEventListener('click',()=>viewer.close());
 viewer.querySelector('[data-photo-prev]').addEventListener('click',()=>show(selected-1));viewer.querySelector('[data-photo-next]').addEventListener('click',()=>show(selected+1));
 viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();show(selected+(e.key==='ArrowRight'?1:-1));}});
 viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close();});
 viewer.addEventListener('close',()=>opener?.focus({preventScroll:true}));
 let touchX;viewer.addEventListener('touchstart',e=>{touchX=e.touches[0].clientX;},{passive:true});viewer.addEventListener('touchend',e=>{if(touchX==null)return;const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>60)show(selected+(dx<0?1:-1));touchX=null;},{passive:true});
 render();document.querySelector('#life-caption').textContent='把日常挂起来。点一张照片，慢慢看。';
 status.textContent='新增与删除仅保存在此浏览器。';
 storage.then(()=>new Promise((resolve,reject)=>{const request=db.transaction('album').objectStore('album').get('state');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);})).then(saved=>{if(saved&&!published){for(const id of saved.removed||[])removed.add(id);const next=photos.filter(p=>!removed.has(p.id)).map(p=>({...p,caption:typeof saved.captions?.[p.id]==='string'?saved.captions[p.id]:p.caption})).concat(saved.custom||[]);const byId=new Map(next.map(p=>[p.id,p]));const ordered=(saved.order||[]).flatMap(id=>{const photo=byId.get(id);byId.delete(id);return photo?[photo]:[];});photos.splice(0,photos.length,...ordered,...byId.values());render();}gallery.dataset.ready='true';}).catch(()=>{status.textContent='浏览器存储不可用，仍可浏览已有照片。';gallery.dataset.ready='true';});
 window.portfolioAlbum={render,photos};
})();
